spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://restaurants-hb.cofnpqculw2y.us-east-1.rds.amazonaws.com:3306/hb-restaurants
#    url: jdbc:mysql://localhost:3306/hb_restaurants
    username: root
    password: hb-be-pass-01
  mail:
    host: smtp.gmail.com
    port: 587
    username: hungerbash@gmail.com
    password: Restaurant@123
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

management:
  security:
    enabled: false
    
app:
  paging:
    size: 10